name: Publish
on:
    push:
        branches:
            - "main"
    workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.config }}

permissions:
    contents: write
    pull-requests: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v2
              with:
                  version: 10

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "pnpm"

            - run: pnpm install --frozen-lockfile

            - name: Create Release Pull Request or Publish
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
